name = "omkara-admin"
pages_build_output_dir = ".vercel/output/static"
account_id = "d59cdccc5f8113995cb2ac03851efeb3"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Bind our free-tier KV namespace
[[kv_namespaces]]
binding = "MANIFEST_KV"
id = "4dabf9b4f7444e17a21e26ea4897ab40"

